services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - .:/var/www/html
    ports:
      - "9001:80"
    networks:
      - app-network
    depends_on:
      - app_db

  app_db:
    image: mariadb:10.3
    container_name: app_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jin
      MYSQL_USER: jin
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
